### ISSUE TITLE
error in getRecursions "Not compatible with requested type" that can not be debugged

### ISSUE THREAD

**Issue by rsmiller74** [cbracis/recurse#2]
I am getting an error when calling getRecursions using a data.frame.  I have tried to debug by looking at the source code but can not determine the error.  The data should work in the function.  See below.

> head(tmp)
           x                       y                                t              id
13045 672819 5536219 2015-03-08 01:02:00 57A.2015
86033 694654 5523683 2015-03-08 03:00:00 57A.2015
30737 695160 5523393 2015-03-08 03:02:00 57A.2015
86035 698207 5521674 2015-03-08 05:02:00 57A.2015
4911  694639 5523749 2015-03-08 06:00:00 57A.2015
5398  694549 5523802 2015-03-08 06:02:00 57A.2015
 
> sapply(tmp, class)
$x
[1] "numeric"

$y
[1] "numeric"

$t
[1] "POSIXlt" "POSIXt" 

$id
[1] "character"

> recurse::getRecursions(tmp, radius=100)

Error in getRecursionsCpp(x[, 1], x[, 2], x[, 3], x[, 4], x[, 1], x[,  :Not compatible with requested type: [type=list; target=double].

**Comment by cbracis** [comment]
Hi, the data format looks correct, and if I try getRecursions() with just the subset you've shown here, it works. Can you provide the data that produces the error?

**Comment by cbracis** [comment]
Note that this error can occur if you pass a tibble. Try converting to a regular data frame to use the function.
