### ISSUE TITLE
Error with getRecursionsInPolygon - if (isNewTrack[j]) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by CamiloCarneiro** [cbracis/recurse#3]
Hi,

I am trying to use the getRecursionsInPolygon() function, but I keep getting the following error (and additional warning):
```
Error in if (isNewTrack[j]) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In diff(as.numeric(trajectory[, idIdx])) : NAs introduced by coercion
```
Am I failing in providing something that the function needs?

I am providing a data.frame with locations and timestamps, as required:

```
         x       y           timestamp  id
1 501658.0 4290020 2020-10-18 17:55:00 tag
2 505927.4 4293400 2020-10-18 18:25:00 tag
3 505914.5 4293368 2020-10-18 18:55:00 tag
4 499876.1 4287707 2020-10-18 10:25:00 tag
5 499794.4 4287576 2020-10-18 10:55:00 tag
6 499790.5 4287579 2020-10-18 11:25:00 tag
...

```
Similarly, I am providing a SpatialPolygons object such as:
```
An object of class "SpatialPolygons"
Slot "polygons":
[[1]]
An object of class "Polygons"
Slot "Polygons":
[[1]]
An object of class "Polygon"
Slot "labpt":
[1]  503510.9 4294866.7

Slot "area":
[1] 32165780

Slot "hole":
[1] FALSE

Slot "ringDir":
[1] 1

Slot "coords":
         [,1]    [,2]
[1,] 503886.7 4298520
[2,] 507815.9 4294444
[3,] 502844.6 4291035
[4,] 499396.6 4295706
[5,] 503886.7 4298520



Slot "plotOrder":
[1] 1

Slot "labpt":
[1]  503510.9 4294866.7

Slot "ID":
[1] "ID1"

Slot "area":
[1] 32165780



Slot "plotOrder":
[1] 1

Slot "bbox":
        min       max
x  499396.6  507815.9
y 4291034.9 4298519.7

Slot "proj4string":
CRS arguments: +proj=utm +zone=29 +ellps=WGS84 
```

Thank you in advance!

**Comment by cbracis** [comment]
Hi, from the error it sounds like there are missing values in your id column, could you verify this?

**Comment by CamiloCarneiro** [comment]
There were no missing values, but it seems that the type of variable was causing the error. I had it as character, but after transforming it to factor or numeric it immediately worked. Many thanks!

Suggestion:
After running the function, I got some negative 'timeInside' due to wrongly attributed entrances and exists, which where rooted to the data frame not ordered by timestamp. Easy to fix (and then it worked well), but maybe you want to implement that ordering in getRecursionsInPolygon(), or maybe mention it in the help file (sorry if it is and I missed it)?

Thank you very much for creating 'recurse'!

**Comment by cbracis** [comment]
Great, glad that is working and that you find the package useful. 
It's usually standard to work with trajectory data sorted in order, but I can add a warning for this case, thanks for the feedback!
