### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [cbracis/recurse#4]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`recurse` suggests `rgeos` but does not pass CMD check when `rgeos` is absent:
[00check.log](https://github.com/cbracis/recurse/files/11285343/00check.log)
Here CMD check was run in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path. Possibly the `geos` package would provide mitigations; see also links from https://r-spatial.org/r/2023/04/10/evolution3.html for further hints. Please fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
@cbracis See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.

**Comment by rsbivand** [comment]
@cbracis When `rgeos` is archived in October 2023, your package will fail CRAN checks. I attach my current check log: 
[00check.log](https://github.com/cbracis/recurse/files/12327015/00check.log)
Action is urgently required. The example and the test must condition on the availability of rgeos (that will buy you a little time), but the functionality of your package depends on replacing use of rgeos with alternatives, such as sf, terra, or geos/libgeos.

**Comment by rsbivand** [comment]
@cbracis R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos. It remains the case that many packages importing the raster package needlessly depend on retiring packages, as raster stopped using them a year ago.

**Comment by cbracis** [comment]
Migrated to sf in version 1.3 and above
